### ISSUE TITLE
cannot install zathura using --with-synctex

### ISSUE THREAD

**Issue by xxyxxyxyx1** [zegervdv/homebrew-zathura#28]
I'm trying to install zathura with syntex for use with vimtex. 

`brew doctor` is clean. Here's the output of `brew install zathura --with-synctex` :

> mccec0678:~ mathe$ brew install zathura --with-synctex
Updating Homebrew...
==> Installing zathura from zegervdv/zathura
==> Installing dependencies for zegervdv/zathura/zathura: synctex
==> Installing zegervdv/zathura/zathura dependency: synctex
==> Downloading https://github.com/barracks510/synctexdir/archive/master.zip
Already downloaded: /Users/mathe/Library/Caches/Homebrew/synctex-1.18.0.zip
==> gcc -D__SYNCTEX_WORK__ -Wall -I. -lz -shared synctex_parser.c synctex_parser_utils.c -o libsynctex.dylib
Last 15 lines from /Users/mathe/Library/Logs/Homebrew/synctex/01.gcc:
2018-05-14 14:06:22 +0200
gcc -D__SYNCTEX_WORK__ -Wall -I. -lz -shared synctex_parser.c synctex_parser_utils.c -o libsynctex.dylib
synctex_parser.c:270:12: fatal error: '/usr/include/zlib.h' file not found
\#               include "/usr/include/zlib.h"
            __________            ^~~~~~~~~~~~~~~~~~~~~
1 error generated.
If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/zegervdv/homebrew-zathura/issues

Any suggestions? Thanks

**Comment by zegervdv** [comment]
Maybe try installing zlib?
I’m not near a computer right now so I can’t find the right package name but a brew search should help you find what you need. 

I’ll add it as a dependency if it works for you.

**Comment by xxyxxyxyx1** [comment]
I ran `brew install zlib`, but it installed as keg-only:

`This formula is keg-only, which means it was not symlinked into /usr/local,
because macOS already provides this software`

So I have zlib already, but homebrew is unable to use it to install zathura. 

(I tried `brew install zathura --with-synctex` again, but got the same result as before)

**Comment by zegervdv** [comment]
In that case you’ll have to do brew link zlib before installing and brew unlink zlib afterwards so it can find it during install.

**Comment by zegervdv** [comment]
I've just pushed a fix for it, please check if it works for you and close this issue if that's the case.

**Comment by xxyxxyxyx1** [comment]
Linking and unlinking zlib seemed to work – `brew info zathura` shows a checkmark for --with-synctex. 

I'm still not able to use zathura with vimtex via synctex, but that may be a problem with vimtex. How would you suggest I verify that zathura+synctex is working, without involving vimtex?

**Comment by zegervdv** [comment]
To be honest, I've never used synctex before, so I have no idea if it actually works as it should.

Did you manage to figure it out?

**Comment by xxyxxyxyx1** [comment]
No, I never got it working. I am now using Skim.

**Comment by Merlinwhu** [comment]
I don't know why the "zlib" generates the error, but I have succeeded in installing vimtex + Zathura in macOs vim editor, learned a lot from your issue, thanks!
